version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install

build: off

test: off

deploy_script:
  - IF DEFINED APPVEYOR_REPO_TAG_NAME npm run publish:win
