version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - npm install

test_script:
  - npm test

deploy_script:
  - npm run publish:win
    on:
      appveyor_repo_tag: true
